version: '3'
services:
  kafka:
    container_name: "kafka"
    image: "landoop/fast-data-dev"
    ports:
     - "2181:2181"
     - "3030:3030"
     - "8081:8081"
     - "8082:8082"
     - "8083:8083"
     - "9092:9092"
     - "9581:9581"
     - "9582:9582"
     - "9583:9583"
     - "9584:9584"
     - "9585:9585"
    environment:
      ADV_HOST: "127.0.0.1"
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: "30000"

# docker run --rm -p 2181:2181 -p 3030:3030 -p 8081-8083:8081-8083 \
#        -p 9581-9585:9581-9585 -p 9092:9092 -e ADV_HOST=192.168.99.100 \
#        landoop/fast-data-dev

# docker run --rm -it --net=host landoop/fast-data-dev bash

  elk:
    container_name: "elk"
    image: "sebp/elk"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"