version: '3.1'
services:
  kafka:
    container_name: landoop-kafka
    image: landoop/fast-data-dev:2.2.0
    ports:
     - 2181:2181
     - 3030:3030
     - 8081-8083:8081-8083
     - 9092:9092
     - 9581-9585:9581-9585
    environment:
      ADV_HOST: 127.0.0.1
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
      SAMPLEDATA: 0
      RUNTESTS: 0